In [57]:
import pandas as pd
import numpy as np

In [58]:
hr = pd.read_csv('HR.csv')

In [59]:
hr.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
ExitDate                      1544
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
dtype: int64

In [60]:
hr.shape

(3150, 39)

In [61]:
hr.columns

Index(['Unnamed: 0', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating', 'Employee ID', 'Survey Date',
       'Engagement Score', 'Satisfaction Score', 'Work-Life Balance Score',
       'Training Date', 'Training Program Name', 'Training Type',
       'Training Outcome', 'Location', 'Trainer', 'Training Duration(Days)',
       'Training Cost'],
      dtype='object')

In [62]:
hr.dtypes

Unnamed: 0                      int64
FirstName                      object
LastName                       object
StartDate                      object
ExitDate                       object
Title                          object
Supervisor                     object
ADEmail                        object
BusinessUnit                   object
EmployeeStatus                 object
EmployeeType                   object
PayZone                        object
EmployeeClassificationType     object
TerminationType                object
TerminationDescription         object
DepartmentType                 object
Division                       object
DOB                            object
State                          object
JobFunctionDescription         object
GenderCode                     object
LocationCode                    int64
RaceDesc                       object
MaritalDesc                    object
Performance Score              object
Current Employee Rating         int64
Employee ID                     int64
Survey Date                    object
Engagement Score                int64
Satisfaction Score              int64
Work-Life Balance Score         int64
Training Date                  object
Training Program Name          object
Training Type                  object
Training Outcome               object
Location                       object
Trainer                        object
Training Duration(Days)         int64
Training Cost                 float64
dtype: object

In [63]:
columns_to_remove = ['Unnamed: 0','FirstName','LastName','ADEmail','DOB','State','Location','Title','Training Cost','Training Duration(Days)','Trainer','Location','Training Date','Survey Date','TerminationDescription','TerminationType','Supervisor']

In [64]:
hr = hr.drop(columns=columns_to_remove)

In [65]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   StartDate                   3150 non-null   object
 1   ExitDate                    1606 non-null   object
 2   BusinessUnit                3150 non-null   object
 3   EmployeeStatus              3150 non-null   object
 4   EmployeeType                3150 non-null   object
 5   PayZone                     3150 non-null   object
 6   EmployeeClassificationType  3150 non-null   object
 7   DepartmentType              3150 non-null   object
 8   Division                    3150 non-null   object
 9   JobFunctionDescription      3150 non-null   object
 10  GenderCode                  3150 non-null   object
 11  LocationCode                3150 non-null   int64
 12  RaceDesc                    3150 non-null   object
 13  MaritalDesc                 3150 non-null   object
 14  Performance Score           3150 non-null   object
 15  Current Employee Rating     3150 non-null   int64
 16  Employee ID                 3150 non-null   int64
 17  Engagement Score            3150 non-null   int64
 18  Satisfaction Score          3150 non-null   int64
 19  Work-Life Balance Score     3150 non-null   int64
 20  Training Program Name       3150 non-null   object
 21  Training Type               3150 non-null   object
 22  Training Outcome            3150 non-null   object
dtypes: int64(6), object(17)
memory usage: 566.1+ KB

In [66]:
hr.drop_duplicates()

,StartDate,ExitDate,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,JobFunctionDescription,...,MaritalDesc,Performance Score,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Program Name,Training Type,Training Outcome
0,20-Sep-19,NaN,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,Accounting,...,Widowed,Fully Meets,4,3427,1,2,3,Leadership Development,Internal,Failed
1,11-Feb-23,NaN,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,Labor,...,Widowed,Fully Meets,3,3428,2,1,5,Customer Service,External,Incomplete
2,10-Dec-18,NaN,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,Assistant,...,Widowed,Fully Meets,4,3429,1,2,1,Leadership Development,External,Failed
3,21-Jun-21,NaN,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,Clerk,...,Single,Fully Meets,2,3430,5,5,4,Project Management,External,Completed
4,29-Jun-19,NaN,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,Laborer,...,Married,Fully Meets,3,3431,2,5,3,Technical Skills,External,Failed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,22-Jun-22,07-Aug-22,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Production,Engineers,Model Assistant,...,Widowed,Fully Meets,3,3422,1,1,3,Communication Skills,Internal,Failed
2996,28-Dec-20,NaN,SVG,Active,Part-Time,Zone A,Full-Time,Production,Engineers,Engineer,...,Widowed,Fully Meets,3,3423,4,5,3,Technical Skills,External,Completed
2997,09-Dec-20,04-Aug-22,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Production,Wireline Construction,Laborer,...,Single,Fully Meets,2,3424,2,4,5,Project Management,Internal,Completed
2998,28-May-19,23-Oct-21,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Production,Aerial,Foreman,...,Divorced,Fully Meets,2,3425,5,2,3,Technical Skills,External,Completed
2999,27-Apr-22,NaN,BPC,Active,Full-Time,Zone B,Temporary,Production,Field Operations,Warehouse Technician,...,Married,Fully Meets,2,3426,1,3,2,Leadership Development,Internal,Failed

In [67]:
hr.isna().sum()

StartDate                        0
ExitDate                      1544
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
DepartmentType                   0
Division                         0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Program Name            0
Training Type                    0
Training Outcome                 0
dtype: int64

In [68]:
hr['ExitDate'] = hr['ExitDate'].fillna("active")

In [69]:
hr.head()

,StartDate,ExitDate,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,JobFunctionDescription,...,MaritalDesc,Performance Score,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Program Name,Training Type,Training Outcome
0,20-Sep-19,active,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,Accounting,...,Widowed,Fully Meets,4,3427,1,2,3,Leadership Development,Internal,Failed
1,11-Feb-23,active,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,Labor,...,Widowed,Fully Meets,3,3428,2,1,5,Customer Service,External,Incomplete
2,10-Dec-18,active,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,Assistant,...,Widowed,Fully Meets,4,3429,1,2,1,Leadership Development,External,Failed
3,21-Jun-21,active,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,Clerk,...,Single,Fully Meets,2,3430,5,5,4,Project Management,External,Completed
4,29-Jun-19,active,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,Laborer,...,Married,Fully Meets,3,3431,2,5,3,Technical Skills,External,Failed

In [70]:
hr.isna().sum()

StartDate                     0
ExitDate                      0
BusinessUnit                  0
EmployeeStatus                0
EmployeeType                  0
PayZone                       0
EmployeeClassificationType    0
DepartmentType                0
Division                      0
JobFunctionDescription        0
GenderCode                    0
LocationCode                  0
RaceDesc                      0
MaritalDesc                   0
Performance Score             0
Current Employee Rating       0
Employee ID                   0
Engagement Score              0
Satisfaction Score            0
Work-Life Balance Score       0
Training Program Name         0
Training Type                 0
Training Outcome              0
dtype: int64

In [71]:
hr = hr.rename(columns={'RaceDesc':'Race'
                   ,'MaritalDesc':'Marital Status'})

In [72]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   StartDate                   3150 non-null   object
 1   ExitDate                    3150 non-null   object
 2   BusinessUnit                3150 non-null   object
 3   EmployeeStatus              3150 non-null   object
 4   EmployeeType                3150 non-null   object
 5   PayZone                     3150 non-null   object
 6   EmployeeClassificationType  3150 non-null   object
 7   DepartmentType              3150 non-null   object
 8   Division                    3150 non-null   object
 9   JobFunctionDescription      3150 non-null   object
 10  GenderCode                  3150 non-null   object
 11  LocationCode                3150 non-null   int64
 12  Race                        3150 non-null   object
 13  Marital Status              3150 non-null   object
 14  Performance Score           3150 non-null   object
 15  Current Employee Rating     3150 non-null   int64
 16  Employee ID                 3150 non-null   int64
 17  Engagement Score            3150 non-null   int64
 18  Satisfaction Score          3150 non-null   int64
 19  Work-Life Balance Score     3150 non-null   int64
 20  Training Program Name       3150 non-null   object
 21  Training Type               3150 non-null   object
 22  Training Outcome            3150 non-null   object
dtypes: int64(6), object(17)
memory usage: 566.1+ KB

In [73]:
hr['StartDate']= pd.to_datetime(hr['StartDate'])

C:\Users\Mitul\AppData\Local\Temp\ipykernel_31800\4170521565.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hr['StartDate']= pd.to_datetime(hr['StartDate'])

In [74]:
hr["EmployeeStatus"] = hr["EmployeeStatus"].replace({
    'Future Start':'Active',
    'Voluntarily Terminated':'Terminated',
    'Leave of Absence':'Active',
    'Terminated for Cause':'Terminated'
})

In [75]:
hr["EmployeeStatus"].nunique()

2

In [76]:
hr["EmployeeStatus"].unique()

array(['Active', 'Terminated'], dtype=object)

In [77]:
hr.to_csv('HR_cleaned_2.csv')